2021-01-22 16:25:43,688 ERROR: Exception on /reserve [GET] [in /Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: reservation.r_user, reservation.agent

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/smarigowda/UI_code/Scheduler/Device_Reservation/app/routes.py", line 149, in reserve
    db.session.commit()
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2540, in flush
    self._flush(objects)
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2642, in _flush
    flush_context.execute()
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    statement, params
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/Users/smarigowda/UI_code/Scheduler/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: reservation.r_user, reservation.agent
[SQL: INSERT INTO reservation (agent, timestamp, duration, r_user) VALUES (?, ?, ?, ?)]
[parameters: ('vcal3', '2021-01-23 00:25:43.688474', '5', 'sqa_user')]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-23 11:29:55,252 INFO: Device Reservation startup [in /Users/smarigowda/UI_code/Scheduler/Device_Reservation/app/__init__.py:49]
2021-01-23 11:30:01,917 INFO: Device Reservation startup [in /Users/smarigowda/UI_code/Scheduler/Device_Reservation/app/__init__.py:49]
2021-01-23 11:31:43,532 INFO: Device Reservation startup [in /Users/smarigowda/UI_code/Scheduler/Device_Reservation/app/__init__.py:49]
2021-01-23 11:31:55,471 INFO: Device Reservation startup [in /Users/smarigowda/UI_code/Scheduler/Device_Reservation/app/__init__.py:49]
2021-01-23 12:34:36,107 INFO: Device Reservation startup [in /Users/smarigowda/UI_code/Scheduler/Device_Reservation/app/__init__.py:49]
2021-01-23 12:34:49,028 INFO: Device Reservation startup [in /Users/smarigowda/UI_code/Scheduler/Device_Reservation/app/__init__.py:49]
2021-01-23 12:34:56,760 INFO: Device Reservation startup [in /Users/smarigowda/UI_code/Scheduler/Device_Reservation/app/__init__.py:49]
2021-01-23 12:35:03,354 INFO: Device Reservation startup [in /Users/smarigowda/UI_code/Scheduler/Device_Reservation/app/__init__.py:49]
2021-01-23 12:35:09,903 INFO: Device Reservation startup [in /Users/smarigowda/UI_code/Scheduler/Device_Reservation/app/__init__.py:49]
2021-01-23 12:35:23,000 INFO: Device Reservation startup [in /Users/smarigowda/UI_code/Scheduler/Device_Reservation/app/__init__.py:49]
